# Generated by Django 4.1.5 on 2023-05-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_task_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('เพศทางเลือก', 'เพศทางเลือก')], default='ชาย', max_length=15)),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('กราฟิก', 'กราฟิก'), ('IT', 'IT'), ('บัญชี', 'บัญชี')], default='กราฟิก', max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
