# Generated by Django 4.1.5 on 2023-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
