# Generated by Django 4.1.5 on 2023-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_employee_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], default=1, max_length=100)),
            ],
        ),
    ]
