# Generated by Django 4.1.5 on 2023-05-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='phone',
        ),
    ]
